# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
ribbon:
# 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
# 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000

# feign调用超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000